# Generated by Django 6.0.1 on 2026-05-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='available_seats',
            field=models.IntegerField(default=30),
        ),
    ]
